cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    instance:
      data:
        enabled: false
    sns:
      enabled: false

server:
  forward-headers-strategy: framework
