cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    instance:
      data:
        enabled: false
    sns:
      enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


  application:
    name: todoapp

server:
  forward-headers-strategy: framework
