name: 04 - Publish Todo-App

on:
  push:
    paths:
      - 'application/**' 
      - 'cdk/**/*Service*' 
      - 'cdk/pom.xml'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    name: Build and publish Todo App 
    steps:
    
    - name: Create Docker image tag
      id: dockerImageTag
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}"
      
    - name: Publish Docker image to ECR registry 
      if: github.ref == 'refs/heads/main'
      ...
      
    - name: Sending deployment event to queue 
      if: github.ref == 'refs/heads/main' 
      env:
        DOCKER_IMAGE_TAG: ${{ steps.dockerImageTag.outputs.tag }} 
      run: |
        export EVENT_PAYLOAD="\
            {\"commitSha\": \"$GITHUB_SHA\",\
           \"ref\": \"main\", \
           \"owner\": \"Zueon\", \
           \"repo\": \"teammade-aws\", \
           \"workflowId\": \"05-update-todo-app-in-staging.yml\", \
           \"dockerImageTag\": \"$DOCKER_IMAGE_TAG\"}"
        aws sqs send-message \
          --queue-url=https://.../todoapp-deploymentsQueue.fifo \
          --message-group-id default \
          --message-deduplication-id $GITHUB_SHA \
          --message-body "$EVENT_PAYLOAD"
